#!/bin/bash

sleep 2

# set vars
if [ ! $PRIVATE_KEY ]; then
	read -p "Enter token: " PRIVATE_KEY
	echo 'export PRIVATE_KEY='$PRIVATE_KEY >> $HOME/.bash_profile
fi

sudo apt update
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn -y
git clone https://github.com/scroll-tech/scroll-contract-deploy-demo.git
cd scroll-contract-deploy-demo
yarn install
cp .env.example .env
sed -i 's/0xabc123abc123abc123abc123abc123abc123abc123abc123abc123abc123abc1/$PRIVATE_KEY/g' .env
yarn compile
yarn deploy:scrollTestnet
yarn test
