#!/bin/bash

sleep 2

sudo apt update && sudo apt install -y curl git build-essential pkg-config libssl-dev
sudo curl https://sh.rustup.rs --proto '=https' --tlsv1.2 -sSf | sh -s -- -y
source $HOME/.cargo/env
rustup update
git clone https://github.com/anoma/namada-trusted-setup.git
cd namada-trusted-setup && git checkout v1.0.1
cargo build --release --bin namada-ts --features cli
mv target/release/namada-ts /usr/local/bin
screen -S anoma_setup

