#!/bin/bash

if [ ! $PRIVATEKEY ]; then
	read -p "Enter private key: " PRIVATEKEY
	echo 'export PRIVATEKEY='$PRIVATEKEY >> $HOME/.bash_profile
fi

echo -e "\e[1m\e[32m2. Install docker-compose \e[0m" && sleep 1
cd $HOME
sudo apt update && sudo apt purge docker docker-engine docker.io containerd docker-compose -y
rm /usr/bin/docker-compose /usr/local/bin/docker-compose
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

sudo apt install git -y
git clone https://github.com/ObolNetwork/charon-distributed-validator-node.git
chmod o+w charon-distributed-validator-node
cd charon-distributed-validator-node
docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.9.0 create enr
echo $PRIVATEKEY >| .charon/charon-enr-private-key

echo "Press any key to continue"
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "waiting for the keypress"
fi

docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.9.0 create enr
